export { CallToAction, CustomersSay, Specials, testimonialCard, HomePage } from './Home';
export { default as AboutPage } from './About/AboutPage';
export { default as MenuPage } from './Menu/MenuPage';
export { BookingPage, ConfirmBookingPage, BookingForm } from './Booking';
export { OrderCard, OrdersSummary, OrderOnlinePage } from './Orders';
export { LoginForm, SignUpForm, LoginPage, SignUpPage, LogoutPage, ProfilePage } from './Auth';
export { Chicago, DishCard, ErrorMsg, LoginErrorMsg } from './SharedComponents';
export { Header, Footer, ScrollToTop } from './Layout';
export { default as WelcomePage } from './Welcome/WellcomePage';
export { default as NotAllowedPage } from './NotAllowed/NotAllowedPage';
export { default as NotFoundPage } from './NotFound/NotFoundPage';
