export {
  getStoredClient,
  storeClient,
  removeStoredClient,
  getStoredOrders,
  storeOrders,
  removeStoredOrders,
} from './storage';
export { initializeTimes, updateTimes } from './times';
export {
  isFormValid,
  isSignUpFormValid,
  isLoginFormValid,
  validateDate,
  validateTime,
  validateNumOfGuests,
  validateName,
  validateEmail,
  validatePhone,
  validatePassword,
  validateConfirmPassword,
  isValidDate,
  isValidTime,
  isValidNumOfGuests,
  isValidName,
  isValidEmail,
  isValidPhone,
  isValidPassword,
  isValidConfirmPassword,
} from './validate';
